version: 2
updates:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
  # TODO: https://github.com/dependabot/dependabot-core/issues/4364
  - directory: "/test-suite"
    package-ecosystem: "npm"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
    - dependency-name: "*"
  - directory: "/test-suite"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
    - dependency-name: "*"
