FROM ubuntu:18.04
ARG VERSION

COPY scripts/docker-install-build.bash /tmp/docker-install-build.bash
RUN /tmp/docker-install-build.bash

ENV PATH="/usr/local/go/bin:$PATH"

COPY go.mod go.sum scripts/docker-prefetch.bash /tmp/
RUN /tmp/docker-prefetch.bash

COPY . /upm
RUN make -C /upm upm

FROM ubuntu:18.04

COPY scripts/docker-install-languages.bash /tmp/docker-install-languages.bash
RUN /tmp/docker-install-languages.bash

COPY --from=0 /upm/cmd/upm/upm /usr/local/bin/upm
