[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "one_dep"
authors = [{name = "Developer Experience", email = "devex@repl.it"}]
dynamic = ["version", "description"]
dependencies = ["django>=4.2.6,<5.0.0"]
